### ISSUE TITLE
右键图标-->New 没反应

### ISSUE THREAD

**Issue by ghost** [imlinhanchao/sticky_notes#5]
win10 LTSC

下载的zip包

有什么环境要求么？

**Comment by imlinhanchao** [comment]
需要系统有 Webview2 的组件。可以到这里下载安装：https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section 如果提示已经安装了，应该是某些原因没有识别到，那么就找到 `msedgewebview.exe` 的位置，然后在软件设置界面上，勾选 `自定义 Webview Runtime` 选择 `msedgewebview.exe` 的路径再重新启动即可。
